### ISSUE TITLE
Cannot deserialize types when simplified qualified name is not resolvable by .NET framework

### ISSUE THREAD

**Issue by alexvaut** [akkadotnet/Hyperion#117]
To reproduce, add this test in Hyperion.Tests:

        [Fact]
        public void CanSerializeColor()
        {
		var expected = Color.Aquamarine;
	        Serialize(expected);
	        Reset();
	        var actual = Deserialize<Color>();
	        Assert.Equal(expected, actual);
        }

This test in all the .NET core versions will pass but not the one in .NET framework.
The reason is that "System.Drawing.Color, System.Drawing" is not a fully qualified type name in .NET framework.

**Comment by Aaronontheweb** [comment]
@alexvaut is this still the case after #116 - could you please send a PR with this test?
