### ISSUE TITLE
.Net Core 3.0 support

### ISSUE THREAD

**Issue by jxlarrea** [akkadotnet/Hyperion#118]
On .Net Core 3.0 (releases today), Hyperion's constructor throws an exception:

`System.TypeInitializationException: 'The type initializer for 'Hyperion.SerializerOptions' threw an exception.'`

This was properly reported in issue #111 about 6 months ago. Is this project still being maintained?

**Comment by Danthar** [comment]
fixed with #119

**Comment by bromanko** [comment]
Thanks! When can we expect a new release to be published with this fix?

**Comment by Danthar** [comment]
To be determined. But I'd expect it not to take to long. While on the
subject are there any other Pr's you would find essential to merge before
we release?

Op vr 4 okt. 2019 19:28 schreef Brian Romanko <notifications@github.com>:

**Comment by bromanko** [comment]
This is the only thing that looks to be completely blocking. At the moment you cannot run Akka.NET using remoting/cluster with .Net Core 3.

**Comment by Danthar** [comment]
To be fair, there are more issues with running akka.net on .Net Core 3. We have gotten multiple reports on different things.
