### ISSUE TITLE
 Insecure deserialization

### ISSUE THREAD

**Issue by games** [akkadotnet/Hyperion#239]
Hi there, just want to know is that true?

Security advisories: https://github.com/AsynkronIT/Wire/security/advisories/GHSA-hpw7-3vq3-mmv6

> Due to how Wire handles type information in its serialization format, malicious payloads can be passed to a deserializer. e.g. using a surrogate on the sender end, an attacker can pass information about a different type for the receiving end. And by doing so allowing the serializer to create any type on the deserializing end.
> This is the same issue that exists for .NET BinaryFormatter https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2300?view=vs-2019
> This also applies to the fork of Wire, **AkkaDotNet/Hyperion.**

**Comment by Aaronontheweb** [comment]
@games this applies to any form of polymorphic serialization - so yes that affects Hyperion. We have a PR here that I'm reviewing now that implements a solve for this: https://github.com/akkadotnet/Hyperion/pull/242

**Comment by Aaronontheweb** [comment]
Related: https://github.com/akkadotnet/Hyperion/issues/226

**Comment by Aaronontheweb** [comment]
Resolved via #242
