### ISSUE TITLE
How to avoid deserialization of untrusted data attacks with Hyperion serializer?

### ISSUE THREAD

**Issue by Arkatufus** [akkadotnet/Hyperion#275]
### Discussed in https://github.com/akkadotnet/akka.net/discussions/5329

<div type='discussions-op-text'>

<sup>Originally posted by **jonnydee** October 19, 2021</sup>
We are currently using Akka 1.4 with Hyperion serialization configured for all user messages sent between Akka systems. We want to make sure Hyperion cannot be tricked into deserialization of untrusted data (see [CWE-502](https://cwe.mitre.org/data/definitions/502.html) for details about that matter).

I know about Hyperion's `akka.actor.serialization-settings.hyperion.disallow-unsafe-type` configuration option which can be used to enable a built-in blacklist for dangerous types. This approach doesn't suffice in our case, however, because we need to trust that the built-in blacklist currently is complete and also will remain complete in the future. Note that being forced to upgrade Akka to some newer release just because new/missing types might have been added to the blacklist is not an option for us. Being able to configure types on the blacklist ourselves would surely be an improvement but the general problem of an outdated blacklist would still remain. It would just be a shift in who is responsible / trusted to have the most recent and complete list of types on the blacklist.

We would like to have an option for a whitelist approach where we list all types that are allowed to be deserialized explicitly. I looked into Hyperion's "Pre-Configured Types" mechanism which involves an [`IKnownTypesProvider`](https://getakka.net/api/Akka.Serialization.IKnownTypesProvider.html). I hoped it would allow us to configure known types explicitly while at the same time ruling out unknown ones. Please correct if I am wrong, but it seems like this is not the case. Instead, known types would be replaced by some id (which is good) but "unknown" types would still be serialized with type information (which is bad). Furthermore, Hyperion's current implementation for mapping ids to known types seems to depend on the order of the types returned by `IKnownTypesProvider.GetKnownTypes()` method. (The id corresponds to the type's position in the returned `IEnumerable<Type>`.) This makes an approach where known message types are collected by some automatism (e.g. a reflection-based approach) difficult, because all involved Actor Systems would have to see exactly the same list (size/items/order) of known types even though some of them would never see all messages in that "overall" list.

We know that using some schema-based serialization technology (e.g. Google's Protocol Buffers) doesn't suffer from such attack vectors but, unfortunately, we cannot use it in our product. Also securing communication between Actor Systems using a VPN is not an option for us.

So the questions are:

- Is there some other way to defend against untrusted data attacks when using Hyperion?
- Do you have any idea on how to implement a whiltelisting machanism for Hyperion in an easy and future-proof way?</div>

We need to find a way to configure black and white listing of types for the Hyperion serializer.

- [x] Add Whitelist/blacklist implementation
- [ ] Improve KnownValueProvider to not depend on array index for its manifest id

**Comment by Arkatufus** [comment]
# Hyperion security update

## General improvements

In SerializerOptions class:
- `IEnumerable<Type> knownType` .ctor parameter should be changed to `IDictionary<ushort, Type> knownTypes`
- `Type[] KnownTypes` should be changed to `Dictionary<ushort, Type> KnownTypes`
- Changes would be made so that it is backward compatible with the old .ctor

In Serializer class:
- `ValueSerializer[] _knownValueSerializers` should be changed to `Dictionary<ushort, ValueSerializer> _knownValueSerializerMap` 

In SerializerSession:
- _nextTypeId should be initialized with serializer.Options.KnownTypes.Max(kvp => kvp.Key) instead of array length
- _trackedTypes should be changed to `Dictionary<ushort, Type>`

In DeserializerSession:
- _offset should be initialized with serializer.Options.KnownTypes.Max(kvp => kvp.Key) instead of array length
- _identifierToType should also be changed to `Dictionary<ushort, Type>

User known types ID will be limited from 0 to 32768 (half a ushort) because we need to make sure that there are enough leeway for the dynamic IDs, this will be checked during serializer initialization

Reasoning:
As of now value serializer manifest index is based on an array index of the `knownTypes` type array passed in the option, this is bad because manifest can only be added, not removed. 

## Whitelist/blacklist implementation

### Base interface design 

Use callback method:

```c#
public interface ITypeFilter
{
    bool IsAllowed(string typeName);
}
```

### Strict list type using a builder pattern

```c#
var myFilter = TypeFilterBuilder.Create()
   .Include<TMessage1>()
   .Include<TMessage2>()
   .Include<TMessage3>()
   .Build();
```

* Build pattern should return an implementation of the callback interface. 

### Default implementation

```
public class TypeFilter: ITypeFilter
{
    public string FullName { get; }
    public string AssemblyName { get; }
}
```

* It would use a simple lookup internally for performance reasons
* Should split and store the type full name and assembly name in string
* Assembly name should not contain versioning and public key token information
* To check for equality, the input is split on the first `,` char
  * index 0 should be compared to the type full name
  * index 1 should be compared to the assembly name
  * index 2, if exists, has to match "%core%"

**Comment by Aaronontheweb** [comment]
> Changes would be made so that it is backward compatible with the old .ctor

Need to ensure wire compatibility too. We should probably save some output from previous versions of the serializer into binary files and incorporate those directly into the repository for forwards-compatibility. For backwards compat we'll need a test harness that can be programmed to run using older versions of Hyperion to read output created from a newer version.

Maybe we can just create a set of Docker images to do this?

**Comment by Aaronontheweb** [comment]
```csharp
public interface ITypeFilter
{
    bool IsAllowed(string typeName);
}
```

I like the idea that this is the top-level interface and only a single one of these should be passed into the options / settings class. If this method returns `false` then we log a warning / error and drop the message.

Users could, in theory, compose multiple of these `ITypeFilter`s together on their own and just use boolean logic to wire it up for scenarios such as having per-library filters and only one of them needs to return `true` in order for the message to be processed.

I like the idea of having a default implementation of the `ITypeFilter` that simply contains an array of strings containing "simple" type names (identical to how they're exposed in Hyperion's wire format, otherwise it wouldn't work) and a builder that allows the user to produce those strings by supplying the set of types. Users could extend those builders to include assembly-scanning, "find all types that inherit this interface"-type functionality but that's not really our job. Provide something that is simple and secure.

I think the design so far here looks good - the wire compat is going to be the biggest concern...

**Comment by Arkatufus** [comment]
Wire format compatibility would be a bit hard to do since the manifest id would be different if the user uses a different indexing scheme compared to the old implementation, and leaving it to the user to make their indexing scheme compatible with the old implementation is a bit of a tall order...

**Comment by Arkatufus** [comment]
The thing that will break compatibility is the manifest id changes, and its a bit hard to separate the implementation so that we can maintain both the old and new implementation working at the same time, since it is tightly woven into the code. We defer the manifest id changes and just do the security update to maintain compatibility for now.

**Comment by Aaronontheweb** [comment]
> The thing that will break compatibility is the manifest id changes, and its a bit hard to separate the implementation so that we can maintain both the old and new implementation working at the same time, since it is tightly woven into the code. We defer the manifest id changes and just do the security update to maintain compatibility for now.

Separating the concerns is a good idea. We should probably resume our years'-old project to formalize the wire format.

**Comment by Arkatufus** [comment]
Reopening this because it is only half solved

**Comment by Aaronontheweb** [comment]
Ah, is this because of the known types providers?

**Comment by Arkatufus** [comment]
Yes, I'll open a new issue instead
