### ISSUE TITLE
Port to .NET Core

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/Hyperion#3]
At this point it's not quite clear, how much of the work is missing in order to being able to use serializer on projects using .NET Core. We need to investigate that and make it happen.

**Comment by alexvaluyskiy** [comment]
It has already supports netcore

**Comment by alexpantyukhin** [comment]
On the current state it doesn't support .NET Core. Actually there are some small compilation problems and some tests are fail under .Net core (all `DelegateTests` tests and some of reflection Infos tests).

**Comment by alexvaluyskiy** [comment]
Done
