### ISSUE TITLE
Add a nuget icon

### ISSUE THREAD

**Issue by SimonCropp** [akkadotnet/Hyperion#54]
Minor, but can we have a nuget icon.

Do u want a PR? I find https://thenounproject.com a good source

I went with https://thenounproject.com/term/beetle/861510/ for https://github.com/SimonCropp/NServiceBus.Hyperion

**Comment by Aaronontheweb** [comment]
I think for the time being we're piggy-backing off of Akka.NET's own logo in the most recent NuGet package metadata.

**Comment by Aaronontheweb** [comment]
But we should do this!
