### ISSUE TITLE
Linux / x-plat build support

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/Hyperion#7]
Need to ensure that tests run on the following environments:

1. [x] .NET full
2. [x] .NET Core (once #3 is implemented)
3. [ ] Mono 

All of the above should target the same version of the .NET Standard, which will likely be 2.0 as part of the Akka.NET 1.5 release.

**Comment by alexvaluyskiy** [comment]
I could take this issue

**Comment by alexvaluyskiy** [comment]
Done
