### ISSUE TITLE
Serialize structs with readonly fields

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/Hyperion#8]
In the present shape, the serializer will not be able to deserialize structs having some private readonly fields in them. What does that mean. It means that following C# 6 struct will throw an exception upon deserialization:

```csharp
public struct MyStruct 
{
    public int Value1 { get; }      // this will fail - hidden readonly field
    public readonly string Value2; // this will fail too
    public MyStruct(int value1, string value2)
    {
        Value1 = value1;
        Value2 = value2;
    }
}
```

So far current compiler tried to set private readonly fields limitations by using reflection. For structs this won't work. Using `FieldInfo.SetValue` or `FieldInfo.SetValueDirect` will throw exception here. However we may try to utilize a special case here - C# compiler ensures that all readonly fields must be initialized in a struct constructor.

@Scooletz : maybe you have some ideas over here. I've seen your proposition on direct mapping from byte chunks to structs, but this must also work with reference types in them.

**Comment by Scooletz** [comment]
Can we use emit here? I think that following construction could work (assuming the created `struct` is held in a local variable.

[Ldloca_S](https://msdn.microsoft.com/en-us/library/system.reflection.emit.opcodes.ldloca_s(v=vs.110).aspx) - to load its address
[Ldflda](https://msdn.microsoft.com/en-us/library/system.reflection.emit.opcodes.ldflda(v=vs.110).aspx) - to load fields address
[Stfld](https://msdn.microsoft.com/en-us/library/system.reflection.emit.opcodes.stfld(v=vs.110).aspx) - to store the value in the field (via address)

Thoughts?

**Comment by Horusiath** [comment]
@Scooletz I haven't tested it yet, but your idea could work if only current version was using `IlCompiler` for generating custom serializers for objects/structs. However it seems that all code gen is done through [DefaultCodeGenerator](https://github.com/akkadotnet/Hyperion/blob/dev/Hyperion/DefaultCodeGenerator.cs) which uses only expression-based compiler. I didn't found address related [Expression](https://msdn.microsoft.com/en-us/library/system.linq.expressions.expression%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396) constructors.

Replacing default code gen with IL-based one is a more ambitious task.

**Comment by Scooletz** [comment]
@Horusiath You can't do it with `Expressions`. Only IL-emit can use addresses.

**Comment by Horusiath** [comment]
I've only fixed the core of an issue. Using custom IL-based serializer code gen now have a separate issue (see: #10).
