### ISSUE TITLE
Ignore Properties

### ISSUE THREAD

**Issue by csharpdeveloper12** [akkadotnet/Hyperion#91]
Hi,

is it possible to extend the `IgnoreAttribute` to use it with properties?

In the implementation its only allowed for fields:
`[AttributeUsage(AttributeTargets.Field, AllowMultiple = false, Inherited = true)]`

**Comment by Horusiath** [comment]
@csharpdeveloper12 Hyperion by default doesn't recognize existence of things such as properties. Everything is made on fields. This can be made, but it will require more work in the guts of the generic `ObjectSerializerFactory`. I'm not sure when we'll have time for this, but any contributions on that field are welcome.

**Comment by csharpdeveloper12** [comment]
I'll see whether i need it. At the Moment i try diffent ways...
But if Hyperion will be the chosen framework, i can send/publish the Code :)
