### ISSUE TITLE
Support System.Uri

### ISSUE THREAD

**Issue by AndreSteenbergen** [akkadotnet/Hyperion#98]
Complex objects can't be serialized if System.Uri is part of the properties. Can't convert string into Uri exception occurs while deserializing.

**Comment by zbynek001** [comment]
do you have preserveObjectReferences setting set to true?
if yes, then it could be related to https://github.com/akkadotnet/Hyperion/issues/96

do you have any details of the exception?

**Comment by AndreSteenbergen** [comment]
It's actually the same issue, duplicate
